### ISSUE TITLE
MACDH seems to have extraneous 2x?

### ISSUE THREAD

**Issue by mcowger** [jealous/stockstats#12]
Looking at the various definitions I can find on the MACD histogram, Everything I can find simply defines it as the difference between the MACD and the 9 period signal line.  Various tools like tradingview, cryptowatch, etc. use this as the definition, as does investopedia.

However in comparing the data I get from stockstats, it appears that a doubling modifier is added:

`df['macdh'] = 2 * (df['macd'] - df['macds'])`

Why is that?  I can't find anything to support such a formula.  If you agree, I'm happy to submit my PR.

**Comment by jealous** [comment]
Hi @mcowger ,
Thanks for the suggestion.
The reason is that the stock software I used to verify the correctness doubles the value.
You are not the first one to mention this problem.  My suggestion is to fork your own version and remove `* 2` in it.
And since the lib has already been used by some user, I would need to bump the version to 1.0.0 to indicate it's not backward compatible if I plan to fix this.  I guess the initial thought for this double is to enlarge the difference.  I will leave this open and see if what others think.

**Comment by mcowger** [comment]
I'd make the following arguments in favor of changing now (I've already addressed the issue in my code):

1. You aren't at 1.0 yet, so changes to the underlying API results are still totally allowed and should be expected in favor of being more correct.  I think that the validation software in use is flawed.
2. Anyone writing code that simply calls 'stockstats' as a requirement rather than 'stockstats==x.y.z' is doing it wrong and possibly deserves what they get :).
3. Upon making the change, a `CRITICAL` level `logging` warning could be added to the output of that function to make it clear whats happening.
4. Even if you dont agree - could we at least get a 'do_not_double' Flag added to the function def.

I'm happy to write a PR for any of these.

**Comment by jealous** [comment]
Thanks @mcowger!  Sounds reasonable to me.  A PR is welcome 😄
