### ISSUE TITLE
Can you count forward?

### ISSUE THREAD

**Issue by richardxy** [jealous/stockstats#22]
First, thank you very much for the great work!

It seems that the counting only applies to a number of days in the past. Would it be nice to have the capability to count forward? Say, 'close_3.5_ge_-5_c' means to count the number of times in the future 5 days where close price is more than $3.5.  

Hope this makes sense. Thanks!

**Comment by jealous** [comment]
Count only takes in a positive integer for previous days because usually "future" is unknown.  But this requirement makes sense in historical data analytic.
The problem is that I feel uncomfortable to use a negative number to indicate it's future.  Count applies to a collection, and the size of the collection should always be a positive number.  So I would prefer adding a new symbol like "fc" (stands for "future count") and accept a positive integer.
I will try to add this in 0.3.0.
